apiVersion: v1
kind: ServiceAccount
metadata:
  name: boltrunner-backend
  namespace: boltrunner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: boltrunner-backend
  namespace: boltrunner
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: boltrunner-backend
  namespace: boltrunner
subjects:
  - kind: ServiceAccount
    name: boltrunner-backend
    namespace: boltrunner
roleRef:
  kind: Role
  name: boltrunner-backend
  apiGroup: rbac.authorization.k8s.io
